### ISSUE TITLE
Issues with circ_threshold 

### ISSUE THREAD

**Issue by catchelle** [michaelorella/droppy#5]
Doing a research project in which automating the contact angle measurement would save a lot of time! However, no matter what I do it seems to throw errors in main about circle threshold being undefined even if I also use -c -l to define it. 
Also like others have requested clearer instructions or examples would be helpful. 

C:\Users\user>droppy "filepath\droppy-master\test_images\hydrophobic_flat.avi" --fitType circular --frequency 5
Analyzing C:\Users\mtrigwel\Documents\python\droppy\droppy-master\test_images\hydrophobic_flat.avi
Traceback (most recent call last):
  File "c:\users\userl\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\Scripts\droppy.exe\__main__.py", line 7, in <module>
  File "c:\users\mtrigwel\appdata\local\programs\python\python37\lib\site-packages\droppy\droppy.py", line 473, in main
    _circ_thresh, _lin_thresh, σ,
NameError: name '_circ_thresh' is not defined

**Comment by connorrupnow** [comment]
I am having this issue too

**Comment by SmithCJ47** [comment]
I am also having this issue. Has anyone else been able to resolve it?

**Comment by ArsalanAli915** [comment]
@michaelorella Any one Find out the above error?

**Comment by ArsalanAli915** [comment]
@michaelorella please this eror still persist.

**Comment by kbroaders** [comment]
I figured out how to get this to run. The problem is that pip is installing a previous commit before "Address Refactoring Bugs." I was able to get it to run by cloning this repo to my computer and directly installing from the base directory using `python setup.py install`. After that, running `droppy` from the command line worked on the test images. Good luck!
